# Generated by Django 5.2.11 on 2026-03-16 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0006_add_ping_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Expo push token', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='pingrequest',
            new_name='patrol_api__driver__5e4ee2_idx',
            old_name='patrol_api__driver_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pingrequest',
            new_name='patrol_api__sent_at_b170d8_idx',
            old_name='patrol_api__sent_at_idx',
        ),
        migrations.RenameIndex(
            model_name='pingrequest',
            new_name='patrol_api__status_2e5b27_idx',
            old_name='patrol_api__status_idx',
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['session', 'timestamp'], name='patrol_api__session_bcbb01_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['timestamp'], name='patrol_api__timesta_2977f0_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['session'], name='patrol_api__session_bcb4bc_idx'),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['user', 'is_active'], name='patrol_api__user_id_60f355_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['token'], name='patrol_api__token_9821bf_idx'),
        ),
    ]
