# Generated by Django 5.2.11 on 2026-03-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0007_add_pushtoken_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('REJECTED', 'Rejected'), ('MISSED', 'Missed')], default='RINGING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='gpslog',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters (lower is better)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='accuracy_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quality score from 0.0 to 1.0 (higher is better)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether this GPS point passed validation checks'),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Reason for rejection if validation failed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Speed in meters per second', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['is_valid'], name='patrol_api__is_vali_120b03_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['accuracy'], name='patrol_api__accurac_e194b2_idx'),
        ),
        migrations.AddField(
            model_name='videocall',
            name='initiator',
            field=models.ForeignKey(help_text='User who started the call (typically admin)', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocall',
            name='recipient',
            field=models.ForeignKey(help_text='User who received the call (typically driver)', on_delete=django.db.models.deletion.CASCADE, related_name='received_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocall',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional associated patrol session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_calls', to='patrol_api.driversession'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['initiator', 'status'], name='patrol_api__initiat_9fbfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['recipient', 'status'], name='patrol_api__recipie_cc4a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['status', 'started_at'], name='patrol_api__status_0b418a_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['session'], name='patrol_api__session_a35325_idx'),
        ),
    ]
