# Generated by Django 5.2.11 on 2026-03-30 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0009_fix_gps_decimal_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('shift_type', models.CharField(max_length=50)),
                ('required_shots', models.JSONField(default=list)),
                ('optional_shots', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('vehicle_type', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('pre_shift', 'Pre-Shift'), ('post_shift', 'Post-Shift')], max_length=20)),
                ('shot_type', models.CharField(choices=[('front', 'Front View'), ('rear', 'Rear View'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('odometer', 'Odometer'), ('fuel_gauge', 'Fuel Gauge'), ('interior', 'Interior'), ('damage', 'Damage Documentation'), ('tires', 'Tires'), ('equipment', 'Equipment')], max_length=20)),
                ('image', models.ImageField(upload_to='vehicle_photos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/thumbnails/%Y/%m/%d/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('captured_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('image_quality_score', models.FloatField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_retake', 'Needs Retake')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photos', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_photos', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='patrol_api.driversession')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='patrol_api.vehicle')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                ('location_on_vehicle', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_repaired', models.BooleanField(default=False)),
                ('repair_notes', models.TextField(blank=True)),
                ('reporting_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='patrol_api.driversession')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='patrol_api.vehicle')),
                ('photos', models.ManyToManyField(related_name='damage_reports', to='patrol_api.vehiclephoto')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehiclephoto',
            index=models.Index(fields=['vehicle', 'photo_type'], name='patrol_api__vehicle_8f1f13_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclephoto',
            index=models.Index(fields=['officer', 'captured_at'], name='patrol_api__officer_2b9c75_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclephoto',
            index=models.Index(fields=['validation_status'], name='patrol_api__validat_bc0baa_idx'),
        ),
    ]
