# Generated by Django 5.2.11 on 2026-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0010_photorequirement_vehiclephoto_damagereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='submission_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
