# Generated by Django 5.2.11 on 2026-04-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0002_add_submission_id'),
        ('patrol_api', '0011_vehiclephoto_submission_id'),
    ]

    operations = [
    ]
