# Generated by Django 5.0.6 on 2026-04-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0012_merge_20260406_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether this incident has been resolved'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the incident was resolved', null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who resolved this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
