# Generated by Django 5.0.6 on 2026-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0013_incidentreport_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpslog',
            name='heading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Direction/heading in degrees (0-360, where 0=North, 90=East)', max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
