# Generated by Django 5.0.6 on 2026-05-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0014_add_heading_to_gpslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversession',
            name='is_app_offline',
            field=models.BooleanField(default=False, help_text='Mobile app is in offline mode'),
        ),
    ]
